builds:
  - id: consumption
    main: ./cmd/consumption/main.go
    binary: consumption
    ldflags:
      - -X main.Version={{ .Tag }}-{{ .ShortCommit }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

nfpms:
  - license: Apache-2.0
    maintainer: Javad Rajabzadeh <ja7ad@live.com>
    homepage: https://github.com/ja7ad/consumption
    bindir: /usr/local/bin
    description: Process power/energy estimation service
    formats:
      - deb
      - rpm
